//Register Admin
####
POST http://localhost:2000/registeradmin
Content-Type: application/json 
//header : what is the content type

{
    "username": "wani",
    "password": 5678,
    "role": "admin"
}


//Login admin
####
POST http://localhost:2000/AdminLogin
Content-Type: application/json

{
    "username": "farah",
    "password": "12345"
}

####
POST http://localhost:2000/registersecurity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkyYTdlNmRkYWIzMzViMzMxYzQyMmEiLCJ1c2VybmFtZSI6ImZhcmFoIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNDQ4NTg2MSwiZXhwIjoxNzA0NDg5NDYxfQ.c9v2CDUw4aAfOj1j-xxuQUpX6WlVIAK2jOYO8Wlykzo
Content-Type: application/json

{
    "username": "sara",
    "password": "1234",
    "role": "security"
}

####
//Login Security
POST http://localhost:2000/SecurityLogin
Content-Type: application/json

{
    "username": "sara",
    "password": "1234"
}

####

POST http://localhost:2000/registerUser
Content-Type: application/json 
//header : what is the content type

{
    "username": "fifi",
    "password": 334455,
    "role": "user"
}

####

POST http://localhost:2000/loginUser
Content-Type: application/json

{
    "username": "Syazwina",
    "password": "22222"
}

//Admin can register visitor
####
POST http://localhost:2000/registervisitor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTk4NjBkYTQwNzY4M2Q0YWZiYTg3MDQiLCJ1c2VybmFtZSI6InNhcmEiLCJwYXNzd29yZCI6IjEyMzQiLCJyb2xlIjoic2VjdXJpdHkiLCJpYXQiOjE3MDQ0ODUyODEsImV4cCI6MTcwNDQ4ODg4MX0.BLUgYHodQXPL1lptBYoSj1BP_GzCzj2AO93wgeta1q4
Content-Type: application/json

{
    "Name": "Syana",
    "Phone_Number" : "01234567890",
    "Address": "jalan permai",
    "Floor_Wing": "23k",
    "Whom_to_meet": "zana",
    "Reason_to_meet": "party"
}

####

PUT http://localhost:2000/Update/659872805df9712ade8826f5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTk4NzIwYTVkZjk3MTJhZGU4ODI2ZjQiLCJ1c2VybmFtZSI6IlN5YXp3aW5hIiwicGFzc3dvcmQiOiIyMjIyMiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA0NTUxMDU4LCJleHAiOjE3MDQ1NTQ2NTh9.ZlGUAuS1-dJvVs7zYLFgjFPlBUao2P23JnMyxMafpYI
Content-Type: application/json

{
    "Name": "Syana",
    "Phone_Number" : "01234567890",
    "Address": "jalan permai",
    "Floor_Wing": "23k",
    "Whom_to_meet": "zana",
    "Reason_to_meet": "party"
}

####

GET http://localhost:2000/viewvisitor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTg4NGE5YWVkMDA4YjUwYWUwMjliYzIiLCJ1c2VybmFtZSI6InN5YXoiLCJwYXNzd29yZCI6MTIzNDU2LCJyb2xlIjoidXNlciIsImlhdCI6MTcwMzQzNjg4NiwiZXhwIjoxNzAzNDQwNDg2fQ.2O_cXTjRadFi43H0eLPdo1koMkF_6vRSGpdypTtftPc

####
GET http://localhost:2000/viewuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkyYTdlNmRkYWIzMzViMzMxYzQyMmEiLCJ1c2VybmFtZSI6ImZhcmFoIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNDQ4NTI1NCwiZXhwIjoxNzA0NDg4ODU0fQ.Bwm5M0YRPX2mUbiPxTkXcavBupNBu7BquSNhnN8VA_o


###

POST http://localhost:2000/issuePass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTg4NGE5YWVkMDA4YjUwYWUwMjliYzIiLCJ1c2VybmFtZSI6InN5YXoiLCJwYXNzd29yZCI6MTIzNDU2LCJyb2xlIjoidXNlciIsImlhdCI6MTcwMzQzMjU2NCwiZXhwIjoxNzAzNDM2MTY0fQ.mkqQDF-0_0vRwXKmdt8976anNECzTorW5tjAgAbNxqI
Content-Type: application/json

{
    "visitorName": "Syana",
    "passType":  "VisitorPass"
}

###
GET http://localhost:2000/retrievePass/Syana
Content-Type: application/json